[pytest]
# VS Code’s built-in Testing UI does not currently surface per-test timing in the Test Results tree.
addopts = -rA --capture=tee-sys --durations=40 -vv
# pytest-timeout safeguard: fail tests that run longer than 120s.
timeout = 120
timeout_method = signal
# Show prints live in the terminal *and* keep them in pytest’s captured output
markers =
    smk: Snakemake workflow tests. These primarily mirror script __main__ entrypoints, use fixtures that follow workflow filepath logic, and may depend on preceding workflow stages already being complete.
    short: Tests expected to run in under 2 seconds.
    network: Tests that require network access.
log_format = %(asctime)s.%(levelname)s.%(name)s:  %(message)s
log_date_format = %M:%S
pythonpath = . smk
testpaths = tests
filterwarnings =
    ignore:The 'shapely\.geos' module is deprecated:DeprecationWarning:pyogrio
