#  Snakemake Workflow Configuration File

# directory of tiles
fathom_tiles_dir: "_inputs/300x300_2tile/00_tiles"

# directory of tile indices
fathom_index_dir: "_inputs/300x300_2tile/00_tile_index"

out_dir: "workflow_outdir"