snakefile: smk/snakefile
cores: 4
retries: 0
max-jobs-per-timespan: "1/1s"



# Global resource pool for your custom resource
# Multi-arg options must be a YAML list of strings
notemp: true
resources:
  api_calls: 4
rerun-triggers:
  - mtime
